# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build and Test

on:
  schedule:
      - cron: '00 09 * * 6'   # Every Saturday
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on:
      - self-hosted
      - macOS

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
