---
name: Swift Build and Test

on:                          # yamllint disable-line rule:truthy
  schedule:
    - cron: '00 09 * * 6'   # Every Saturday
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on:
      - self-hosted

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GPAT }}
          submodules: recursive

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
